valgrind --leak-check=yes --track-origins=yes ./bin/io
valgrind --leak-check=yes --track-origins=yes ./bin/cmp
valgrind --leak-check=yes --track-origins=yes ./bin/add
valgrind --leak-check=yes --track-origins=yes ./bin/sub
valgrind --leak-check=yes --track-origins=yes ./bin/mul
valgrind --leak-check=yes --track-origins=yes ./bin/div
valgrind --leak-check=yes --track-origins=yes ./bin/gcd
valgrind --leak-check=yes --track-origins=yes ./bin/inv_mod
valgrind --leak-check=yes --track-origins=yes ./bin/montgomery
valgrind --leak-check=yes --track-origins=yes ./bin/exp_mod
valgrind --leak-check=yes --track-origins=yes ./bin/is_prime
